In [2]:
import pandas as pd
import urllib
import re
from tld import get_tld
df = pd.read_csv("PhishTank-online-banking-phishing-urls.csv") # Task 0

In [3]:
!pip install tldextract

Requirement already satisfied: tldextract in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (3.4.0)
Requirement already satisfied: requests-file>=1.4 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from tldextract) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from tldextract) (3.3.1)
Requirement already satisfied: idna in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from tldextract) (3.2)
Requirement already satisfied: requests>=2.1.0 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from tldextract) (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.1.0->tldextract) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.1.0->tldextract) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.1.0->tldextract) (2.0.4)
Requirement already satisfied: six in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from requests-file>=1.4->tldextract) (1.16.0)

In [4]:
import tldextract

In [5]:
!pip install python-whois

Requirement already satisfied: python-whois in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (0.8.0)
Requirement already satisfied: future in /Users/IsaacStertzbach/opt/anaconda3/lib/python3.9/site-packages (from python-whois) (0.18.2)

In [6]:
import whois

In [7]:
df

,Indicator type,Indicator,Description
0,URL,http://vysodagiva0.xhost.ro/cibc-online-banking/,NaN
1,URL,ftp://188.128.111.33/IPTV/TV1324/view.html,NaN
2,URL,http://115.28.157.120/Public/upload/file/20170...,NaN
3,URL,http://woodfloorcreations.com/includes/js/tabs...,NaN
4,URL,http://115.28.157.120/Public/upload/file/20170...,NaN
...,...,...,...
403,URL,http://karasserybank.com/da9c13eff2b8731f4bdf1...,NaN
404,URL,http://karasserybank.com/da9c13eff2b8731f4bdf1...,NaN
405,URL,http://karasserybank.com/da9c13eff2b8731f4bdf1...,NaN
406,URL,http://karasserybank.com/da9c13eff2b8731f4bdf1...,NaN
407,URL,http://karasserybank.com/da9c13eff2b8731f4bdf1...,NaN

In [34]:
def is_ip(address):
    return address.replace('.', '').isnumeric()
hostname_list = []
ip_address_list = []
domain_list = []
for url in df['Indicator']:
    hostname_with_path = url.split("//")[1] # Task 1
    hostname_only = hostname_with_path.split("/")[0]
    if is_ip(hostname_only):
        ip_address_list.append(hostname_only)
    else:
        hostname_list.append(hostname_only)
        domain = tldextract.extract(hostname_only).domain
        domain_list.append(domain)

data_df_domain= pd.DataFrame(hostname_list, columns=['hostname'])
data_df_domain['domain'] = domain_list
len(ip_address_list) # Task 2
len(pd.unique(data_df_domain['domain'])) # Task 3
#data_df_domain['domain'].value_counts()

278

In [9]:
data_df_domain

                        hostname              domain
0           vysodagiva0.xhost.ro               xhost
1         woodfloorcreations.com  woodfloorcreations
2               hghsuppliers.com        hghsuppliers
3          marcaldeataide.com.br      marcaldeataide
4    citymarket.imperiavkusov.ru       imperiavkusov
..                           ...                 ...
395            karasserybank.com       karasserybank
396            karasserybank.com       karasserybank
397            karasserybank.com       karasserybank
398            karasserybank.com       karasserybank
399            karasserybank.com       karasserybank

[400 rows x 2 columns]

In [28]:
hostname_list= []
tld_list=[]
subdomain_list=[]
domain_len_list=[]
subdomain_level_list=[]
vowels_count_list=[]
digit_count_list=[]
domain_subdomain = []

for url in df['Indicator']:
    hostname_with_path = url.split("//")[1] 
    
    hostname_only = hostname_with_path.split("/")[0]
    if not is_ip(hostname_only):
        hostname_list.append(hostname_only)
        tld = get_tld(hostname_only, fix_protocol=True)
        tld_list.append(tld)
        subdomain = tldextract.extract(hostname_only).subdomain
        subdomain_list.append(subdomain)
        domain = tldextract.extract(hostname_only).domain
        domain_len_list.append(len(domain))
        if subdomain == '':
            subdomain_level_list.append(0)
        else:
            subdomain_level_list.append(len(subdomain.split(".")))
        vowels_count_domain = [domain.count(x) for x in "aeiou"]
        vowels_count_list.append(sum(vowels_count_domain))
        digits_count_domain = [domain.count(x) for x in "1234567890"]
        digit_count_list.append(sum(digits_count_domain))
        if subdomain == '':
            domain_subdomain.append(domain)
        else:
            domain_subdomain.append(domain + "." + subdomain)
        
data_df= pd.DataFrame(hostname_list, columns=['hostname'])
data_df['TLD']= tld_list
data_df['subdomain'] = subdomain_list
data_df['domain_len'] = domain_len_list
data_df['subdomain_level'] = subdomain_level_list
data_df['vowel_counts']= vowels_count_list
data_df['digit_counts']= digit_count_list
data_df['keywords'] = domain_subdomain

In [35]:
data_df.head(10)

,hostname,TLD,subdomain,domain_len,subdomain_level,vowel_counts,digit_counts,keywords
0,vysodagiva0.xhost.ro,ro,vysodagiva0,5,1,1,0,xhost.vysodagiva0
1,woodfloorcreations.com,com,,18,0,8,0,woodfloorcreations
2,hghsuppliers.com,com,,12,0,3,0,hghsuppliers
3,marcaldeataide.com.br,com.br,,14,0,7,0,marcaldeataide
4,citymarket.imperiavkusov.ru,ru,citymarket,13,1,6,0,imperiavkusov.citymarket
5,www.semazen.net,net,www,7,1,3,0,semazen.www
6,vindetect.cz,cz,,9,0,3,0,vindetect
7,merlyna.tecnologia7.com,com,merlyna,11,1,5,1,tecnologia7.merlyna
8,merlyna.tecnologia7.com,com,merlyna,11,1,5,1,tecnologia7.merlyna
9,merlyna.tecnologia7.com,com,merlyna,11,1,5,1,tecnologia7.merlyna

In [14]:
len(pd.unique(data_df['subdomain'])) # Task 9

44

In [32]:
len(pd.unique(data_df['keywords']))

298

In [16]:
data_df.head(50) # Task 11

,hostname,TLD,subdomain,domain_len,subdomain_level,vowel_counts,digit_counts
0,vysodagiva0.xhost.ro,ro,vysodagiva0,5,1,1,0
1,woodfloorcreations.com,com,,18,0,8,0
2,hghsuppliers.com,com,,12,0,3,0
3,marcaldeataide.com.br,com.br,,14,0,7,0
4,citymarket.imperiavkusov.ru,ru,citymarket,13,1,6,0
5,www.semazen.net,net,www,7,1,3,0
6,vindetect.cz,cz,,9,0,3,0
7,merlyna.tecnologia7.com,com,merlyna,11,1,5,1
8,merlyna.tecnologia7.com,com,merlyna,11,1,5,1
9,merlyna.tecnologia7.com,com,merlyna,11,1,5,1
10,centino.pl,pl,,7,0,3,0
11,allstarprintz.com,com,,13,0,3,0
12,allstarprintz.com,com,,13,0,3,0
13,allstarprintz.com,com,,13,0,3,0
14,banking.onlinesecurityauthority.com,com,banking,23,1,10,0
15,iam1.hunsa.com,com,iam1,5,1,2,0
16,kloudteck.com,com,,9,0,3,0
17,www.olejnik.net.pl,net.pl,www,7,1,3,0
18,suphitoprak.com.tr,com.tr,,11,0,4,0
19,drive.google.com,com,drive,6,1,3,0
20,andoverstonewall.com,com,,16,0,6,0
21,andoverstonewall.com,com,,16,0,6,0
22,ibank.standardchartered.com.my,com.my,ibank,17,1,5,0
23,ankara.eucu.net,net,ankara,4,1,3,0
24,ip-23-229-248-164.ip.secureserver.net,net,ip-23-229-248-164.ip,12,2,5,0
25,brindescerto.com.br,com.br,,12,0,4,0
26,loginh.com,com,,6,0,2,0
27,themovieforum.org,org,,13,0,6,0
28,themovieforum.org,org,,13,0,6,0
29,themovieforum.org,org,,13,0,6,0
30,themovieforum.org,org,,13,0,6,0
31,themovieforum.org,org,,13,0,6,0
32,lederair.net,net,,8,0,4,0
33,www.lederair.net,net,www,8,1,4,0
34,www.lederair.net,net,www,8,1,4,0
35,ebanking-ch1.ubs.com.vissergoutsmits.nl,nl,ebanking-ch1.ubs.com,15,3,5,0
36,out.easycounter.com,com,out,11,1,5,0
37,www.loraboyd.com,com,www,8,1,3,0
38,registeredinvestmentadvisor.blogspot.com,blogspot.com,registeredinvestmentadvisor,8,1,2,0
39,registeredinvestmentadvisor.blogspot.de,blogspot.de,registeredinvestmentadvisor,8,1,2,0
40,gs-aviation.com,com,,11,0,5,0
41,themovieforum.org,org,,13,0,6,0
42,paulscycle.ca,ca,,10,0,3,0
43,cibconlinebanking.net,net,,17,0,6,0
44,dreamhomeloansindia.blogspot.ru,blogspot.ru,dreamhomeloansindia,8,1,2,0
45,dreamhomeloansindia.blogspot.de,blogspot.de,dreamhomeloansindia,8,1,2,0
46,bankruptcyinfoguide.com,com,,19,0,7,0
47,banquesenligne.org,org,,14,0,6,0
48,mowebplus.com,com,,9,0,3,0
49,mowebplus.com,com,,9,0,3,0

In [63]:
data_df.shape

(400, 7)